---
- name: Install and deploy artifact
  hosts: deploy
  become: true

  tasks:
   - name: Install a list of packages
     apt:
      pkg:
      - default-jdk
      - maven
      - git
      update_cache: yes
      state: present
   - name: Just get information about the repository whether or not it has already been cloned locally
     git:
      repo: 'https://github.com/boxfuse/boxfuse-sample-java-war-hello.git'
      dest: /tmp/hello
      clone: yes
      update: no
   - name: Build app
     shell: mvn package chdir="/tmp/hello"

- name: Install tomcat and publish app on the web
  hosts: web
  become: true

  tasks:
   - name: Ensure docker package is present
     apt:
      name: docker.io
      state: present
      update_cache: true

   - name: Ensure docker is running
     service:
      name: docker.service
      state: started

   - name: Install docker-compose from official github repo
     get_url:
       url : https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
       dest: /usr/local/bin/docker-compose
       mode: 755

   - name: Example clone of a single branch
     git:
      repo: https://github.com/egupov/dz8.git
      dest: /root/tomcat
      version: compose

   - name: Transfer file from deploy to web
     synchronize:
      src: /tmp/hello/target/hello-1.0.war 
      dest: /root/tomcat/
     delegate_to: deploy

   - name: Start docker-compose app
     shell:
      chdir: /root/tomcat/
      cmd: docker-compose up -d