- name: Install and deploy artifact
  hosts: deploy
  become: true

  tasks:
   - name: Install a list of packages
     apt:
      pkg:
      - default-jdk
      - maven
      - git
      update_cache: yes
      state: present
   - name: Just get information about the repository whether or not it has already been cloned locally
     git:
      repo: 'https://github.com/boxfuse/boxfuse-sample-java-war-hello.git'
      dest: /tmp/hello
      clone: yes
      update: no
   - name: Build app
     shell: mvn package chdir="/tmp/hello"

- name: Install docker for all && login dockerhub
  hosts: all
  become: true

  tasks:
   - name: Ensure docker package is present
     apt:
      pkg:
      - docker.io
      - python-pip
      state: present
      update_cache: yes

   - name: add docker-py
     shell: pip install docker-py

   - name: Ensure docker is running
     service:
      name: docker.service
      state: started
  
   - name: log into docker hub registry
     docker_login:
       email: "mail"
       username: "user"
       password: "pass"

- name: Build image and push of a dockerhub
  hosts: deploy
  become: true

  tasks:
   - name: Example clone of a single branch
     git:
      repo: https://github.com/egupov/dz8.git
      dest: /root/tomcat
      version: dockerhub

   - name: Transfer file from deploy to web
     copy:
      src: /tmp/hello/target/hello-1.0.war 
      dest: /root/tomcat/hello-1.0.war
      remote_src: True

???????????????????????????????????????????????????
   - name: build container image
     docker_image:
      build: 
        dockerfile:
          source: ./tomcat/Dockerfile
        path: ./tomcat
      source: build
      state: present
      name: tomcat:v1.0

   - name: Tag and push to docker hub
     docker_image:
      name: tomcat:v1.0
      repository: egupoff/dz8
      push: true
      source: local

- name: pull dockerhub image
  hosts: web
  become: true

  tasks:    
   - name: ensure a container is running
     docker_container:
       name: tomcat
       state: started
       image: "egupoff/dz8:master-latest"
       pull: true
       ports:
         - "80:8080"